name: Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo Action
      uses: actions/checkout@v3
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test
